### ISSUE TITLE
Check for correct url if not fix

### ISSUE THREAD

**Issue by caseybecking** [caseybecking/shardupdateo#2]
If you do not have a slash `/` at the end of the url it fails with this message

```
Traceback (most recent call last):
  File "main.py", line 10, in <module>
    download_url.find_sources(dir_path+"/"+target_list[1]+"/")
  File "/usr/local/src/sharkupdateo/download_url.py", line 45, in find_sources
    repo_tags = github_connect.get_repo_tags(repo+'/'+org)
  File "/usr/local/src/sharkupdateo/github_connect.py", line 41, in get_repo_tags
    release = repo.get_latest_release()
  File "/usr/local/lib/python3.7/site-packages/github/Repository.py", line 2501, in get_latest_release
    self.url + "/releases/latest"
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 264, in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/usr/local/lib/python3.7/site-packages/github/Requester.py", line 275, in __check
    raise self.__createException(status, responseHeaders, output)
github.GithubException.UnknownObjectException: 404 {'message': 'Not Found', 'documentation_url': 'https://developer.github.com/v3/repos/releases/#get-the-latest-release'}
```

We need to be able to detect if the url is correct or not.

**Comment by caseybecking** [comment]
This has been fixed.
